# Generated by Django 5.2.3 on 2025-07-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('commercial', 'Commercial'), ('personal', 'Personal')], default='personal', max_length=20)),
                ('category', models.CharField(default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
